name: HashiCorp Packer (main.yml)
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest    
    name: Packer Build new AMI
    steps:
    - uses: actions/checkout@main
    - uses: ./actions/action-a
      env:
        MY_NAME: "Bill Yang"
        MY_AWS_ACCESS: ${{ secrets.MY_AWS_ACCESS }}
        MY_AWS_SECRET: ${{ secrets.MY_AWS_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to test target group
    needs: [build]
    steps:
    - uses: actions/checkout@main
    - uses: ./actions/action-b
      env:
        MY_NAME: "Bill Yang"
  promote:
    runs-on: ubuntu-latest
    name: Promote test target group to live
    needs: [build,deploy]
    steps:
      - name: promote
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: | 
          echo "token is $ACCESS_TOKEN ..."
  scale-down:
    runs-on: ubuntu-latest
    name: Scale down test target group
    needs: [build,deploy,promote]
    steps:
      - name: Scale down
        env:
          MY_VAR: Hi there, now scale down the test target group
        run: | 
          echo "$MY_VAR"
